### ISSUE TITLE
Treats packages as multiple files

### ISSUE THREAD

**Issue by apoydence** [nelsam/vidar#13]
Have you considered treating each package as a single "file"? I haven't really thought about ANY details/implications of this, but I think it could be an interesting take for writing Go code.

**Comment by nelsam** [comment]
That's an interesting thought.  I imagined how this might work for a bit, today... I have some thoughts:

1. How would we open a packaging for editing?
  - Sub-packages suddenly become complicated.  What does a user do if they want to open a package, versus descending into sub-packages of a package?
  - Thinking both in terms of a tree view and in terms of a vim/emacs style find-file command, the meaning of selecting a package to edit becomes interesting.  `gxui.KeyEnter` may mean "edit this package", or it may mean "descend into this package".  The same goes with clicking/double-clicking.
2. How would files be displayed?
  - We (probably) don't want to completely gloss over the fact that files exist
  - I'm thinking a collapsible (default collapsed) scope for each file.  This would make them feel like organizational units within a package.
  - I'm also thinking that, if this is the case, the `package` clause can be hidden from the display.  At this point, the package is what you're editing.
  - I'm thinking it might make sense to have the `package` clause and documentation comments in the package display, and hide it from the per-file display (since it suddenly makes much less sense to display that clause for editing).
    - The implications here get a little weird.  Do we provide a "package comments" section in each file, for things like licensing, package documentation, or build constraints?  Do we go even farther, providing a separate per-project license setting (which automatically gets applied to every file's package comments), a per-package "documentation" section which automatically goes in a file named `doc.go` (a recommendation from [this blog post](http://blog.golang.org/godoc-documenting-go-code)), and a per-file "build constraints" section?  I think I'd find this useful, but is it too opinionated?

I like the idea, in theory.  In practice, the UX may get complicated; but the idea makes a lot of sense.

**Comment by nelsam** [comment]
I've implemented the first piece of this, although I expect it'll need a lot of polish in the near future.  A tree is created from the parsed directory and can be used to navigate.  I'm finding it much, much easier to use than trying to find the file I want to edit ... when it works.

The one big issue I don't have an answer for just yet is: "What happens if a file in the package has a syntax error?  Do we fall back to file-only?  Do we have enough information to highlight the offending file?"

But like I said, I'm finding it easier to navigate a package via its contents than via files.  When the package doesn't have compilation issues, it's a breeze to find the thing I want to edit, even in code that I'm unfamiliar with.

**Comment by nelsam** [comment]
@apoydence When you get a chance, can you take a look at the Table of Contents tree UI, see if it's going in a direction you think makes sense?

**Comment by apoydence** [comment]
I'm not sure I see what UI you are referring to... I'm quite possibly being stupid

**Comment by nelsam** [comment]
The "files" dialog shows a table of contents of functionality for the
currently selected package (including a "files" section for browsing files
directly). Clicking on any of those elements takes you to the correct file.

I don't think it always puts the cursor in the right place, but it's often
correct. That's less important than the general idea, though. I just want
to see if you have other ideas, or if that might cover what you're
basically looking for.

**Comment by nelsam** [comment]
The cursor issue was fixed.  I'm closing this for now.
