### ISSUE TITLE
Not configurable

### ISSUE THREAD

**Issue by darthlukan** [nelsam/vidar#15]
Colors, paths, keybinds, etc should be configurable via a config file.

Possible paths:

$HOME/.vidarrc
$HOME/.config/vidar/config

**Comment by nelsam** [comment]
I've just pushed an update that uses yaml files in ~/.config/vidar/ for project settings.  There are plenty more to come, but it's a start.

I'm not yet respecting $XDG_USER_HOME, but I hope to in the near future.

**Comment by darthlukan** [comment]
:+1:

**Comment by nelsam** [comment]
FWIW, this is all but done now.  There are a few config files, and some behavior can be customized that way.  The rest is customized mostly via plugins (which can, themselves, have data in the config files).  I'm going to mark this as done and open new issues for a few polish bits - namely:

1. shortcut commands to open the settings files (basically menu entries to open those files without needing to know their location)
2. additional logic for highlighting and potentially auto-completing within settings files
3. re-loading the config files while vidar is running
  * this (and some other minor runtime updates, i.e. changing the font size) has been on the backburner for a while _mostly_ because of how gxui handles initialization.  elements of the UI are initialized with a theme (including font and border styles and colors), but most of those elements never re-load any values in the theme after they're initialized.  fixing this may not be trivial.
