### ISSUE TITLE
Error when running "Could not create config file"

### ISSUE THREAD

**Issue by Kvaz1r** [nelsam/vidar#52]
When try to run(Windows 7) I get the message:

> panic: Could not create config file: open C:\Users\╨Р_user\AppData\Roaming\vidar
> \keys.toml: The system cannot find the path specified.

**Comment by nelsam** [comment]
Oh, I know what's going on.  There's logic to create that directory when you add a project, but when I changed it to use a config file for key bindings, I didn't think to include logic to create the directory there.  I'll update that this weekend.

**Comment by nelsam** [comment]
da6c894e083001f40a3ee3608b5c80fa4bd53a26 should have fixed this.  Reopen if it's still broken.

Also, just so you're aware, some of the movement key bindings (ctrl+left and ctrl+right, for example) are currently missing due to the migration to user-bindable keys in that `keys.toml` file.  I'm adding that functionality back as quickly as I can, but it's missing right now.

**Comment by Kvaz1r** [comment]
Yes, now is not falling. However, cannot save the file.

**Comment by nelsam** [comment]
Yep, makes sense.  It *should* write that config file the next time you start it, but I was relying on two `init()` functions running in a specific order when I really shouldn't have been.  I'll update that as well.

**Comment by nelsam** [comment]
78457690de81fd6e74923bfbc87b3f8a5205fac0 should have fixed the latest issue with this.  As before, reopen if you still run in to issues.

**Comment by Kvaz1r** [comment]
Now, can not save with an error
 
> panic: runtime error: slice bounds out of range

Maybe should open a separate issue since the initial solved ?.

**Comment by nelsam** [comment]
Yeah, go ahead and make a separate issue for that.  I'm going to see if I can figure out how to reproduce it on my machine.

**Comment by nelsam** [comment]
I think I discovered the issue you were running in to, but I'm not certain.  I got it to give me an index out of bounds panic, but I don't know for certain that it's the same one you were running in to.

I've pushed a few commits that appear to fix that issue.  If that's the issue you were running in to, I think you should be set, now.

If you're curious, the issue revolved around the `goimports` command in vidar trying to display a helpful status message in the UI.  Unfortunately, if the `goimports` tool isn't installed, the command's attempt to make the message more helpful was causing a panic.  I hadn't seen the issue because I have `goimports` installed on every computer I own.  I even have it on one of the two Windows VMs I was testing it on.

**Comment by Kvaz1r** [comment]
Yes, now it works.
