### ISSUE TITLE
Mac OSX Fails to build

### ISSUE THREAD

**Issue by SCKelemen** [nelsam/vidar#84]
Samuels-MBP:vidar Kelemen$ go run main.go 
# github.com/nelsam/vidar/editor
editor/split_editor.go:410: cannot use int(glfw.ArrowCursor) (type int) as type glfw.StandardCursor in argument to glfw.CreateStandardCursor
editor/split_editor.go:411: cannot use int(glfw.HResizeCursor) (type int) as type glfw.StandardCursor in argument to glfw.CreateStandardCursor
editor/split_editor.go:412: cannot use int(glfw.VResizeCursor) (type int) as type glfw.StandardCursor in argument to glfw.CreateStandardCursor

**Comment by nelsam** [comment]
Thanks for the report!  Looks like we were broken by [this commit](https://github.com/go-gl/glfw/commit/9abafbd0c2bd3f667b290e42a8a0c252c63983e3) in glfw.  I didn't notice because I haven't tried a clean clone in a while.

This should be resolved in fea0a6f1e2bd298db4882a99a81d5f36396cdc11.  If not, please re-open this issue.

**Comment by SCKelemen** [comment]
Builds, what signal is killed instantly.

```Samuels-MBP:vidar Kelemen$ go run main.go 
signal: killed```
