### ISSUE TITLE
Incorrect label for open file 

### ISSUE THREAD

**Issue by Kvaz1r** [nelsam/vidar#97]
If open file by corresponding menu button from disk root - get wrong label for file. 
Example:
![iss1](https://user-images.githubusercontent.com/17313967/31310087-6bd21d84-ab9a-11e7-9b53-ec071b80f597.jpg)

Reason in this [line](https://github.com/nelsam/vidar/blob/master/commands/fslocator.go#L304).
If add this condition:
`&& strings.Count(text,string(filepath.Separator)) > 1 `
or this:
`&& len(text) > 3`
will be work correctly, but I not sure about preservation workability for other platforms.

**Comment by nelsam** [comment]
I believe the problem is actually on [this line](https://github.com/nelsam/vidar/blob/master/commands/fslocator.go#L301), before the one you linked.  It's supposed to check if you're at the root of the file system, but it only works on unix-like platforms.  Windows has more than one root file system (one for each drive).

**Comment by Kvaz1r** [comment]
fixed in #104
